### ISSUE TITLE
LUN being created on incorrect Storage Pool 

### ISSUE THREAD

**Issue by markdand** [emc-openstack/unity-cinder-driver#8]
Hi,

We have 2 storage pools configured on our Unity system, one for capacity and one for performance. Each pool is associated to a volume_type, capacity to unity_cap and performance to unity_ssd, correctly in Cinder.
When we create a unity_cap volume, the LUN gets created correctly in the capacity pool, however, when we create a unity_ssd volume, it too goes to the capacity pool and not the performance pool. The backend name in the Cinder config matches the volume_type name.

Openstack Version: Ocata
Deployed Using: Openstack-Ansible

Sanitised config:
```
...
[unity_cap]
san_password=[]
storage_pool_names=PerformancePool1
volume_backend_name=unity_cap
san_login=[]
volume_driver=cinder.volume.drivers.dell_emc.unity.Driver
san_ip=[]
storage_protocol=FC

[unity_ssd]
san_password=[]
storage_pool_names=SSDPool01
volume_backend_name=unity_ssd
san_login=[]
volume_driver=cinder.volume.drivers.dell_emc.unity.Driver
san_ip=[]
storage_protocol=FC
...
```

Is this a bug in the driver or is something incorrectly configured?

Thanks
Mark

**Comment by peter-wangxu** [comment]
Hi @markdand 
Since you are using ocata, please refer to https://docs.openstack.org/ocata/config-reference/block-storage/drivers/dell-emc-unity-driver.html for driver configuration.

You should use `unity_storage_pool_names` to specify the pool names, seems the configuration file is for an early version (you are using `storage_pool_names` for configuring pools). Besides this above miss config, please do double confirm with the doc and adjust your cinder driver config if needed.

Thanks
Peter

**Comment by markdand** [comment]
Hi Peter,

Thanks, the config change that you suggessted did the trick.

Thanks
Mark
